# Generated by Django 5.2.14 on 2026-05-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('nombre', models.CharField(max_length=120)),
                ('abreviatura', models.CharField(blank=True, max_length=8)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='escudos/')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('barrio', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(default='Córdoba', max_length=80)),
                ('provincia', models.CharField(default='Córdoba', max_length=80)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('posicion', models.CharField(blank=True, max_length=32)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='torneo.equipo')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('puntos_local', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('puntos_visitante', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_juego', 'En juego'), ('finalizado', 'Finalizado'), ('postergado', 'Postergado')], default='programado', max_length=20)),
                ('jornada', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_como_local', to='torneo.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_como_visitante', to='torneo.equipo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='torneo.sede')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneo.torneo')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='torneo.torneo'),
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('puntos', models.PositiveSmallIntegerField(default=0)),
                ('valoracion', models.SmallIntegerField(default=0)),
                ('faltas_personales', models.PositiveSmallIntegerField(default=0)),
                ('faltas_tecnicas', models.PositiveSmallIntegerField(default=0)),
                ('tiros_simples_convertidos', models.PositiveSmallIntegerField(default=0)),
                ('tiros_simples_fallados', models.PositiveSmallIntegerField(default=0)),
                ('tiros_dobles_convertidos', models.PositiveSmallIntegerField(default=0)),
                ('tiros_dobles_fallados', models.PositiveSmallIntegerField(default=0)),
                ('tiros_triples_convertidos', models.PositiveSmallIntegerField(default=0)),
                ('tiros_triples_fallados', models.PositiveSmallIntegerField(default=0)),
                ('rebotes_ofensivos', models.PositiveSmallIntegerField(default=0)),
                ('rebotes_defensivos', models.PositiveSmallIntegerField(default=0)),
                ('asistencias', models.PositiveSmallIntegerField(default=0)),
                ('robos', models.PositiveSmallIntegerField(default=0)),
                ('tapones', models.PositiveSmallIntegerField(default=0)),
                ('perdidas', models.PositiveSmallIntegerField(default=0)),
                ('datos_crudos_ocr', models.JSONField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='torneo.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='torneo.partido')),
            ],
            options={
                'verbose_name_plural': 'estadísticas',
                'unique_together': {('partido', 'jugador')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('torneo', 'categoria', 'nombre')},
        ),
    ]
